heat_template_version: '2015-06-29'
resources:
  my_instance:
    properties: 
      flavor: m1.small
      image: Ubuntu 14.04
      key_name: tco-gold
      user_data: |
          #!/bin/bash
          cd /tmp
          wget http://benincosa.com/test.sh
          chmod 755 /tmp/test.sh
          /tmp/test.sh
    type: OS::Nova::Server
