- name: launch one nova instance
  connection: local
  hosts: local
  gather_facts: false  
  vars_files:
   - vars/metacloud_vars.yml

  tasks: 
 
  - name: Ensure New server is up. 
    nova_compute:
      state: present
      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      login_username: "{{ lookup('env', 'OS_USERNAME') }}"
      login_password: "{{ lookup('env', 'OS_PASSWORD') }}"
      login_tenant_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
      name: demo-server
      image_name: ubuntu-14.04-server
      key_name: chompkey
      flavor_id: 3 
      security_groups: default
