- name: launch one openstack instance
  connection: local
  hosts: local
  gather_facts: false  
  vars_files:
   - vars/metacloud_vars.yml

  tasks: 
 
  - name: Ensure New server is up. 
    nova_compute:
      state: present
      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      login_username: "{{ lookup('env', 'OS_USERNAME') }}"
      login_password: "{{ lookup('env', 'OS_PASSWORD') }}"
      login_tenant_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
      name: ansible-server
      # run nova image-list to get an image and put its id below. 
      image_id: 
      # fill in your key name here
      key_name: 
      flavor_id: 3 
      security_groups: default
